#!/bin/bash
# ============================================
# Maximus Core - Docker Entrypoint Script
# ============================================

set -e

# Configuration defaults
NETWORK=${NETWORK:-mainnet}
MAXIMUSD_OPTS=${MAXIMUSD_OPTS:-}
RPC_USER=${RPC_USER:-maximus}
RPC_PASSWORD=${RPC_PASSWORD:-$(head -c 32 /dev/urandom | base64)}

# Data directory
DATA_DIR="${HOME}/.maximuscore"
CONF_FILE="${DATA_DIR}/maximus.conf"

# ============================================
# Create configuration file if not exists
# ============================================
create_config() {
    if [ ! -f "${CONF_FILE}" ]; then
        echo "Creating default configuration..."
        mkdir -p "${DATA_DIR}"

        cat > "${CONF_FILE}" <<EOF
# Maximus Core Configuration
# Generated by Docker entrypoint

# Network selection (mainnet by default, overridden by -testnet/-regtest flags)
# testnet=1
# regtest=1

# RPC Configuration
rpcuser=${RPC_USER}
rpcpassword=${RPC_PASSWORD}

# Logging
logtimestamps=1
shrinkdebugfile=1

# Performance
dbcache=256
maxconnections=125

# Network settings
listen=1
discover=1
dnsseed=1
upnp=0
natpmp=0

# Network-specific port configuration
# See sections below for testnet/regtest ports
EOF
        chmod 600 "${CONF_FILE}"
        chown maximus:maximus "${CONF_FILE}"
    fi
}

# ============================================
# Update config for network selection
# ============================================
update_config_for_network() {
    # Remove existing [test] and [main] sections if they exist
    sed -i '/^\[test\]/,/^$/d' "${CONF_FILE}" 2>/dev/null || true
    sed -i '/^\[main\]/,/^$/d' "${CONF_FILE}" 2>/dev/null || true
    sed -i '/^testnet=/d' "${CONF_FILE}" 2>/dev/null || true
    sed -i '/^regtest=/d' "${CONF_FILE}" 2>/dev/null || true

    case "${NETWORK}" in
        mainnet)
            # Mainnet - no special config needed, defaults are mainnet
            # Add [main] section just for reference with correct ports
            cat >> "${CONF_FILE}" <<EOF

[main]
rpcport=9938
port=9939
EOF
            ;;
        testnet)
            # Testnet - add testnet=1 at global level (NOT inside [test] section)
            sed -i 's/^# testnet=1$/testnet=1/' "${CONF_FILE}"
            # Add [test] section with testnet-specific ports
            cat >> "${CONF_FILE}" <<EOF

[test]
rpcport=19938
port=19939
EOF
            ;;
        regtest)
            # Regtest - add regtest=1 at global level
            sed -i 's/^# regtest=1$/regtest=1/' "${CONF_FILE}"
            # Add [regtest] section with regtest-specific ports
            cat >> "${CONF_FILE}" <<EOF

[regtest]
rpcport=19838
port=19839
EOF
            ;;
    esac
}

# ============================================
# Handle network selection
# ============================================
setup_network() {
    case "${NETWORK}" in
        mainnet)
            rm -f "${DATA_DIR}/testnet3" 2>/dev/null || true
            rm -f "${DATA_DIR}/regtest" 2>/dev/null || true
            echo "Starting Maximus Core on MAINNET..."
            echo "  Ports: P2P=9939, RPC=9938"
            ;;
        testnet)
            touch "${DATA_DIR}/testnet3/settings.json" 2>/dev/null || true
            rm -f "${DATA_DIR}/regtest" 2>/dev/null || true
            echo "Starting Maximus Core on TESTNET..."
            echo "  Ports: P2P=19939, RPC=19938"
            ;;
        regtest)
            touch "${DATA_DIR}/regtest/settings.json" 2>/dev/null || true
            rm -f "${DATA_DIR}/testnet3" 2>/dev/null || true
            echo "Starting Maximus Core in REGTEST mode..."
            echo "  Ports: P2P=19839, RPC=19838"
            ;;
        *)
            echo "Unknown network: ${NETWORK}"
            echo "Valid options: mainnet, testnet, regtest"
            exit 1
            ;;
    esac
}

# ============================================
# Display version and info
# ============================================
show_info() {
    # Define ports based on network
    case "${NETWORK}" in
        mainnet)
            RPC_PORT_DISPLAY=9938
            PORT_DISPLAY=9939
            ;;
        testnet)
            RPC_PORT_DISPLAY=19938
            PORT_DISPLAY=19939
            ;;
        regtest)
            RPC_PORT_DISPLAY=19938
            PORT_DISPLAY=19939
            ;;
    esac

    echo "=========================================="
    echo "  Maximus Core Docker Container"
    echo "=========================================="
    echo "  Version info:"
    /usr/local/bin/maximusd --version | head -2
    echo ""
    echo "  Configuration:"
    echo "    Network:     ${NETWORK}"
    echo "    Data dir:    ${DATA_DIR}"
    echo "    RPC port:    ${RPC_PORT_DISPLAY}"
    echo "    P2P port:    ${PORT_DISPLAY}"
    echo ""
    echo "  RPC Credentials:"
    echo "    User:        ${RPC_USER}"
    echo "    Password:    [HIDDEN - set RPC_PASSWORD env var]"
    echo ""
    echo "=========================================="
}

# ============================================
# Generate random password on first run
# ============================================
secure_first_run() {
    if [ ! -f "${DATA_DIR}/.configured" ]; then
        echo "First run detected, securing configuration..."
        if [ "${RPC_PASSWORD}" = "" ] || [ ${#RPC_PASSWORD} -lt 16 ]; then
            export RPC_PASSWORD=$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 24)
            sed -i "s/^rpcpassword=.*/rpcpassword=${RPC_PASSWORD}/" "${CONF_FILE}" 2>/dev/null || true
        fi
        touch "${DATA_DIR}/.configured"
    fi
}

# ============================================
# Wait for network/filesystem readiness
# ============================================
wait_ready() {
    local max_wait=30
    local count=0
    echo "Waiting for filesystem to be ready..."
    while [ $count -lt $max_wait ]; do
        if [ -w "${DATA_DIR}" ] || mkdir -p "${DATA_DIR}" 2>/dev/null; then
            return 0
        fi
        sleep 1
        count=$((count + 1))
    done
    echo "Warning: Filesystem not ready after ${max_wait}s"
}

# ============================================
# Graceful shutdown handler
# ============================================
shutdown_handler() {
    echo "Received shutdown signal, stopping maximusd..."
    /usr/local/bin/maximus-cli stop 2>/dev/null || true
    exit 0
}

trap shutdown_handler SIGTERM SIGINT SIGHUP

# ============================================
# Main execution
# ============================================
main() {
    echo "Starting Maximus Core entrypoint..."

    # Wait for filesystem
    wait_ready

    # Create config if needed
    create_config

    # Update config for network selection (set testnet=1 or regtest=1)
    update_config_for_network

    # Secure first run
    secure_first_run

    # Setup network
    setup_network

    # Show info
    show_info

    # Build command with config file
    CMD="/usr/local/bin/maximusd"
    ARGS="-conf=${CONF_FILE}"

    # Add network-specific port settings via command line
    case "${NETWORK}" in
        mainnet)
            # Mainnet: P2P=9939, RPC=9938
            ARGS="${ARGS} -port=9939"
            ;;
        testnet)
            # Testnet: P2P=19939, RPC=19938 (testnet=1 already in config)
            ARGS="${ARGS} -port=19939 -rpcport=19938"
            ;;
        regtest)
            # Regtest: P2P=19839, RPC=19838 (regtest=1 already in config)
            ARGS="${ARGS} -port=19839 -rpcport=19838"
            ;;
    esac

    # Add extra options from environment
    if [ -n "${MAXIMUSD_OPTS}" ]; then
        ARGS="${ARGS} ${MAXIMUSD_OPTS}"
    fi

    # If arguments passed (like -printtoconsole), add them to the command
    if [ -n "$1" ]; then
        echo "Adding provided arguments: $@"
        ARGS="${ARGS} $@"
    fi

    echo "Starting maximusd with: ${CMD} ${ARGS}"
    echo ""

    # Execute
    exec ${CMD} ${ARGS}
}

main "$@"